[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs@4"

[[edge_functions]]
  path = "/propiedades/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/en/propiedades/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/blog/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/en/blog/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"
