[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_GOOGLE_MAPS_API_KEY = "AIzaSyDFHHIhz6Xh-ZdFahhh-MzUoup7d25vbX0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/propiedades/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/en/propiedades/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"
