[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP_FORMS = "true"
  NETLIFY_NEXT_VERIFY_FORMS = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  path = "/propiedades/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/en/propiedades/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/blog/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/en/blog/*"
  function = "inject-meta"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"

[[redirects]]
  from = "/reseñas"
  to = "/resenas"
  status = 301
  force = true

[[redirects]]
  from = "/rese%C3%B1as"
  to = "/resenas"
  status = 301
  force = true
