headersOrigin = "inline"
redirects = []

[build]
edge_functions = "C:\\Users\\lenovo\\Desktop\\Gelabert Homes\\04_Desarrollo_y_Sistemas\\WEB\\frontend\\netlify\\edge-functions"
publish = "C:\\Users\\lenovo\\Desktop\\Gelabert Homes\\04_Desarrollo_y_Sistemas\\WEB\\frontend\\.next"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\lenovo\\Desktop\\Gelabert Homes\\04_Desarrollo_y_Sistemas\\WEB\\frontend"
command = "npm run build"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP_FORMS = "true"
NETLIFY_NEXT_VERIFY_FORMS = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
path = "/propiedades/*"
function = "inject-meta"

[[edge_functions]]
path = "/en/propiedades/*"
function = "inject-meta"

[[edge_functions]]
path = "/blog/*"
function = "inject-meta"

[[edge_functions]]
path = "/en/blog/*"
function = "inject-meta"

[[edge_functions]]
path = "/sitemap.xml"
function = "sitemap"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"